# kustomization.yml
resources:
- https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

patchesJson6902:
- path: deployment-patch.yml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: metrics-server
    namespace: kube-system
